version: '3.4'

services:
  server:
    build: server
    image: server
    restart: 'no'
    volumes:
      - ./server/:/server
      - ./server-cache/:/server-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-server
    image: postgres:14.1
    restart: 'no'
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
